import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireAdminSession } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { notifyUser } from '@/lib/notify';
import { writeAuditLog } from '@/lib/audit';
const input=z.object({title:z.string().min(3).max(180),body:z.string().min(5).max(5000),audience:z.enum(['ALL','CUSTOMER','PROFESSIONAL','ADMIN']),priority:z.enum(['NORMAL','IMPORTANT','URGENT']).default('NORMAL'),publish:z.boolean().default(false)});
export async function GET(){const session=await requireAdminSession();if(!session)return NextResponse.json({error:'Admin permission required.'},{status:403});const rows=await prisma.systemAnnouncement.findMany({orderBy:{createdAt:'desc'},take:30});return NextResponse.json({announcements:rows})}
export async function POST(request:Request){const session=await requireAdminSession();if(!session)return NextResponse.json({error:'Admin permission required.'},{status:403});const body=await request.json().catch(()=>null);const parsed=input.safeParse(body);if(!parsed.success)return NextResponse.json({error:'Title, message and audience are required.'},{status:400});const announcement=await prisma.systemAnnouncement.create({data:{title:parsed.data.title,body:parsed.data.body,audience:parsed.data.audience,priority:parsed.data.priority,status:parsed.data.publish?'PUBLISHED':'DRAFT',publishAt:parsed.data.publish?new Date():null,createdById:session.userId}});if(parsed.data.publish){const where=parsed.data.audience==='ALL'?{status:'ACTIVE' as const}:parsed.data.audience==='ADMIN'?{status:'ACTIVE' as const,role:{in:['ADMIN','SUPER_ADMIN'] as any}}:{status:'ACTIVE' as const,role:parsed.data.audience};const users=await prisma.user.findMany({where,select:{id:true}});await Promise.all(users.map(u=>notifyUser({userId:u.id,type:'SYSTEM_ANNOUNCEMENT',title:parsed.data.title,body:parsed.data.body,link:'/dashboard/notifications'}).catch(()=>{})));}await writeAuditLog({userId:session.userId,action:parsed.data.publish?'ANNOUNCEMENT_PUBLISHED':'ANNOUNCEMENT_CREATED',entity:'SystemAnnouncement',entityId:announcement.id,data:{audience:parsed.data.audience,priority:parsed.data.priority}});return NextResponse.json({announcement})}
