import { NextResponse } from 'next/server';
import { jwtVerify } from 'jose';
import { randomBytes } from 'crypto';
import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { createSupabaseAuthUser, deleteSupabaseAuthUser, getSupabaseAuthUserById } from '@/lib/supabase-admin';
import { createSession, dashboardPath } from '@/lib/auth';
import { createDeviceToken, ensureDevice, deviceHash, recordLoginAttempt } from '@/lib/security';
import { attributeReferral } from '@/lib/referrals';
import { writeAuditLog } from '@/lib/audit';

const input=z.object({role:z.enum(['CUSTOMER','PROFESSIONAL']),accountType:z.enum(['INDIVIDUAL','BUSINESS']),businessName:z.string().max(160).optional(),registrationNumber:z.string().max(60).optional(),phone:z.string().min(7).max(20).optional(),country:z.string().max(80).optional(),state:z.string().max(80).optional(),city:z.string().max(80).optional(),area:z.string().max(120).optional(),street:z.string().max(200).optional(),profession:z.string().max(120).optional(),yearsExperience:z.coerce.number().int().min(0).max(60).optional(),privacyAccepted:z.literal(true),privacyPolicyVersion:z.string().max(40),referralCode:z.string().max(40).optional()});
function secret(){const value=process.env.AUTH_SECRET;if(!value)throw new Error('AUTH_SECRET is required');return new TextEncoder().encode(value);}
export async function GET(request:Request){const token=request.headers.get('cookie')?.match(/(?:^|;\s*)tp_google_pending=([^;]+)/)?.[1];if(!token)return NextResponse.json({error:'No pending Google sign-up.'},{status:404});try{const {payload}=await jwtVerify(token,secret());return NextResponse.json({email:payload.email,name:payload.name});}catch{return NextResponse.json({error:'Google sign-up session expired.'},{status:400});}}
export async function POST(request:Request){
 const token=request.headers.get('cookie')?.match(/(?:^|;\s*)tp_google_pending=([^;]+)/)?.[1];if(!token)return NextResponse.json({error:'Your Google sign-up session expired. Please start again.'},{status:400});
 let authUserId:string|null=null;
 try{
  const {payload}=await jwtVerify(token,secret());const email=typeof payload.email==='string'?payload.email.trim().toLowerCase():'';const sub=typeof payload.sub==='string'?payload.sub:'';const name=typeof payload.name==='string'?payload.name:'';if(!email||!sub||!name)return NextResponse.json({error:'Google account details could not be confirmed.'},{status:400});
  const parsed=input.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please complete the required account details.'},{status:400});const d=parsed.data;if(d.accountType==='BUSINESS'&&(!d.businessName?.trim()||!d.registrationNumber?.trim()))return NextResponse.json({error:'Business name and registration number are required.'},{status:400});
  let existing=await prisma.user.findFirst({where:{OR:[{googleSubject:sub},{email}]}});
  if(existing){try{const authState=await getSupabaseAuthUserById(existing.id);if(!authState.missing)return NextResponse.json({error:'That Google account is already registered. Please sign in instead.'},{status:409});await prisma.user.update({where:{id:existing.id},data:{status:'DELETED',deletedAt:new Date(),deletedEmail:existing.email,deletedPhone:existing.phone,deletedGoogleSubject:existing.googleSubject,email:`deleted-${existing.id}@deleted.truxpylot.invalid`,phone:null,googleSubject:null,suspendedUntil:null,suspensionReason:'Account deleted in Supabase Auth'}});}catch(error){console.error('[google/complete] account reconciliation failed:',error instanceof Error?error.message:error);return NextResponse.json({error:'We could not verify the status of this account right now.'},{status:503});}}
  const randomPassword=randomBytes(32).toString('base64url')+'Aa1!';const authUser=await createSupabaseAuthUser({email,password:randomPassword,emailConfirm:true,userMetadata:{fullName:name,role:d.role,accountType:d.accountType,authProvider:'google',googleSubject:sub}});authUserId=authUser.id;
  const location=[d.area,d.city,d.state].filter(Boolean).join(', ')||undefined;const user=await prisma.user.create({data:{id:authUser.id,email,role:d.role,authProvider:'google',googleSubject:sub,privacyPolicyVersion:d.privacyPolicyVersion,privacyAcceptedAt:new Date(),phone:d.phone||undefined,customer:d.role==='CUSTOMER'?{create:{fullName:name,accountType:d.accountType,businessName:d.businessName,registrationNumber:d.registrationNumber,country:d.country,state:d.state,city:d.city,area:d.area,street:d.street,location}}:undefined,professional:d.role==='PROFESSIONAL'?{create:{fullName:name,accountType:d.accountType,businessName:d.businessName,registrationNumber:d.registrationNumber,country:d.country,state:d.state,city:d.city,area:d.area,street:d.street,location,profession:d.profession,yearsExperience:d.yearsExperience}}:undefined}});
  await writeAuditLog({userId:user.id,action:'PRIVACY_POLICY_ACCEPTED',entity:'PrivacyPolicy',entityId:user.id,data:{version:d.privacyPolicyVersion,acceptedAt:new Date().toISOString()}}).catch(()=>{});if(d.referralCode)await attributeReferral(d.referralCode,user.id,{role:d.role,email}).catch(()=>{});
  const deviceToken=request.headers.get('cookie')?.match(/(?:^|;\s*)tp_device=([^;]+)/)?.[1]||createDeviceToken();const device=await ensureDevice(user.id,deviceToken,request);await recordLoginAttempt({userId:user.id,email,action:'REGISTRATION_GOOGLE',success:true,riskLevel:'NORMAL',request,deviceFingerprint:deviceHash(deviceToken)});const session=await createSession({userId:user.id,role:user.role,email:user.email,deviceId:device.id,twoFactorVerified:false});const response=NextResponse.json({ok:true,redirect:dashboardPath(user.role),emailVerificationPending:false});response.cookies.set('tp_session',session,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:604800});response.cookies.set('tp_device',device.token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:31536000});response.cookies.delete('tp_google_pending');return response;
 }catch(error){if(authUserId)await deleteSupabaseAuthUser(authUserId).catch(cleanupError=>console.error('[google/complete] cleanup failed:',cleanupError instanceof Error?cleanupError.message:cleanupError));console.error('[google/complete]',error instanceof Error?error.message:error);return NextResponse.json({error:'Google sign-up could not be completed. Please try again.'},{status:400});}
}
