import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { z } from 'zod';
import { verifyEmailOtp, normalizeEmail } from '@/lib/otp';
import { prisma } from '@/lib/prisma';
import { createSession, createAuthChallenge, dashboardPath } from '@/lib/auth';
import { ensureDevice, deviceHash, recordLoginAttempt } from '@/lib/security';
const input=z.object({email:z.string().email().transform(normalizeEmail),code:z.string().regex(/^\d{6}$/)});
export async function POST(request:Request){const parsed=input.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Enter the 6-digit email verification code.'},{status:400});const user=await prisma.user.findUnique({where:{email:parsed.data.email},include:{securityProfile:true}});if(!user||user.status!=='ACTIVE')return NextResponse.json({error:'Account recovery is not available.'},{status:403});try{await verifyEmailOtp(parsed.data.email,parsed.data.code)}catch{await recordLoginAttempt({userId:user.id,email:user.email,action:'DEVICE_REVALIDATION',success:false,riskLevel:'HIGH',failureReason:'INVALID_EMAIL_CODE',request});return NextResponse.json({error:'That email verification code is invalid or expired.'},{status:400})}const cookieStore=await cookies();const deviceToken=cookieStore.get('tp_device')?.value;const device=deviceToken?await ensureDevice(user.id,deviceToken,request):null;await recordLoginAttempt({userId:user.id,email:user.email,action:'DEVICE_REVALIDATION',success:true,riskLevel:'NORMAL',request,deviceFingerprint:deviceToken?deviceHash(deviceToken):undefined});if(user.securityProfile?.twoFactorEnabled){const challenge=await createAuthChallenge({userId:user.id,role:user.role,email:user.email,purpose:'LOGIN_2FA'});const response=NextResponse.json({requires2FA:true});response.cookies.set('tp_auth_challenge',challenge,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:600});return response}const token=await createSession({userId:user.id,role:user.role,email:user.email,deviceId:device?.id,twoFactorVerified:false});const response=NextResponse.json({ok:true,redirect:dashboardPath(user.role)});response.cookies.set('tp_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:604800});return response}
