CREATE TYPE "ReferralStatus" AS ENUM ('PENDING','QUALIFIED','REWARDED','REJECTED','EXPIRED');
CREATE TYPE "RewardStatus" AS ENUM ('PENDING','APPROVED','PAID','VOID');
CREATE TYPE "WithdrawalStatus" AS ENUM ('REQUESTED','REVIEWING','APPROVED','PAID','REJECTED');
CREATE TABLE "ReferralCampaign" ("id" text PRIMARY KEY,"name" text NOT NULL,"description" text,"active" boolean NOT NULL DEFAULT true,"rewardAmount" integer NOT NULL DEFAULT 0,"qualificationJobs" integer NOT NULL DEFAULT 1,"startsAt" timestamp(3),"endsAt" timestamp(3),"createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" timestamp(3) NOT NULL);
CREATE TABLE "ReferralMilestone" ("id" text PRIMARY KEY,"campaignId" text NOT NULL,"name" text NOT NULL,"threshold" integer NOT NULL,"rewardAmount" integer NOT NULL,CONSTRAINT "ReferralMilestone_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "ReferralCampaign"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "ReferralMilestone_campaignId_threshold_key" ON "ReferralMilestone"("campaignId","threshold");
CREATE TABLE "ReferralCode" ("id" text PRIMARY KEY,"code" text NOT NULL,"ownerId" text NOT NULL,"campaignId" text,"active" boolean NOT NULL DEFAULT true,"clicks" integer NOT NULL DEFAULT 0,"createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ReferralCode_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "ReferralCode_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "ReferralCampaign"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE UNIQUE INDEX "ReferralCode_code_key" ON "ReferralCode"("code"); CREATE INDEX "ReferralCode_ownerId_active_idx" ON "ReferralCode"("ownerId","active");
CREATE TABLE "ReferralAttribution" ("id" text PRIMARY KEY,"codeId" text NOT NULL,"referredUserId" text NOT NULL,"source" text,"landingPath" text,"metadata" jsonb,"createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ReferralAttribution_codeId_fkey" FOREIGN KEY ("codeId") REFERENCES "ReferralCode"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "ReferralAttribution_referredUserId_fkey" FOREIGN KEY ("referredUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "ReferralAttribution_referredUserId_key" ON "ReferralAttribution"("referredUserId");
CREATE TABLE "Referral" ("id" text PRIMARY KEY,"codeId" text NOT NULL,"referrerId" text NOT NULL,"referredId" text NOT NULL,"campaignId" text,"status" "ReferralStatus" NOT NULL DEFAULT 'PENDING',"qualifiedAt" timestamp(3),"rewardedAt" timestamp(3),"rejectionReason" text,"createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" timestamp(3) NOT NULL,CONSTRAINT "Referral_codeId_fkey" FOREIGN KEY ("codeId") REFERENCES "ReferralCode"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "Referral_referrerId_fkey" FOREIGN KEY ("referrerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "Referral_referredId_fkey" FOREIGN KEY ("referredId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "Referral_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "ReferralCampaign"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE UNIQUE INDEX "Referral_referredId_key" ON "Referral"("referredId"); CREATE INDEX "Referral_referrerId_status_idx" ON "Referral"("referrerId","status"); CREATE INDEX "Referral_status_createdAt_idx" ON "Referral"("status","createdAt");
CREATE TABLE "Reward" ("id" text PRIMARY KEY,"referralId" text,"userId" text NOT NULL,"milestoneId" text,"amount" integer NOT NULL,"status" "RewardStatus" NOT NULL DEFAULT 'PENDING',"reason" text NOT NULL,"approvedById" text,"paidAt" timestamp(3),"createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Reward_referralId_fkey" FOREIGN KEY ("referralId") REFERENCES "Referral"("id") ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT "Reward_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "Reward_milestoneId_fkey" FOREIGN KEY ("milestoneId") REFERENCES "ReferralMilestone"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE INDEX "Reward_userId_status_idx" ON "Reward"("userId","status");
CREATE TABLE "Withdrawal" ("id" text PRIMARY KEY,"userId" text NOT NULL,"amount" integer NOT NULL,"status" "WithdrawalStatus" NOT NULL DEFAULT 'REQUESTED',"bankName" text,"accountName" text,"accountNumber" text,"reviewedById" text,"reviewedAt" timestamp(3),"paidAt" timestamp(3),"createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Withdrawal_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX "Withdrawal_status_createdAt_idx" ON "Withdrawal"("status","createdAt"); CREATE INDEX "Withdrawal_userId_status_idx" ON "Withdrawal"("userId","status");

