'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';

const NG_STATES = ['Abia','Adamawa','Akwa Ibom','Anambra','Bauchi','Bayelsa','Benue','Borno','Cross River','Delta','Ebonyi','Edo','Ekiti','Enugu','FCT (Abuja)','Gombe','Imo','Jigawa','Kaduna','Kano','Katsina','Kebbi','Kogi','Kwara','Lagos','Nasarawa','Niger','Ogun','Ondo','Osun','Oyo','Plateau','Rivers','Sokoto','Taraba','Yobe','Zamfara'];
type Role = 'CUSTOMER' | 'PROFESSIONAL';
type AccountType = 'INDIVIDUAL' | 'BUSINESS';
const SECURITY_QUESTIONS = ['What was the name of your first pet?','What was your childhood nickname?','What was the name of your first school?','What city were you born in?'];

export function RegisterWizard() {
  const router = useRouter();
  const [step,setStep]=useState(0), [role,setRole]=useState<Role|null>(null), [accountType,setAccountType]=useState<AccountType|null>(null);
  const [fullName,setFullName]=useState(''), [businessName,setBusinessName]=useState(''), [registrationNumber,setRegistrationNumber]=useState(''), [email,setEmail]=useState(''), [phone,setPhone]=useState('');
  const [country,setCountry]=useState('Nigeria'), [state,setState]=useState(''), [city,setCity]=useState(''), [area,setArea]=useState(''), [street,setStreet]=useState('');
  const [profession,setProfession]=useState(''), [yearsExperience,setYearsExperience]=useState('');
  const [password,setPassword]=useState(''), [securityQuestion,setSecurityQuestion]=useState(SECURITY_QUESTIONS[0]), [securityAnswer,setSecurityAnswer]=useState(''), [privacyAccepted,setPrivacyAccepted]=useState(false);
  const [submitting,setSubmitting]=useState(false), [error,setError]=useState(''), [otpSent,setOtpSent]=useState(false), [code,setCode]=useState(''), [resendCooldown,setResendCooldown]=useState(0), [referralCode,setReferralCode]=useState(''), [restoringDraft,setRestoringDraft]=useState(true);

  useEffect(()=>{ setReferralCode(new URLSearchParams(window.location.search).get('ref')?.toUpperCase() ?? ''); try { const raw=sessionStorage.getItem('truxpylot_registration_draft'); if(raw){ const d=JSON.parse(raw) as Record<string,unknown>; if(d.role==='CUSTOMER'||d.role==='PROFESSIONAL')setRole(d.role); if(d.accountType==='INDIVIDUAL'||d.accountType==='BUSINESS')setAccountType(d.accountType); for(const [key,setter] of Object.entries({fullName:setFullName,businessName:setBusinessName,registrationNumber:setRegistrationNumber,email:setEmail,phone:setPhone,country:setCountry,state:setState,city:setCity,area:setArea,street:setStreet,profession:setProfession,yearsExperience:setYearsExperience,securityQuestion:setSecurityQuestion})){const v=d[key];if(typeof v==='string')setter(v)} if(d.privacyAccepted===true)setPrivacyAccepted(true); } } catch{} setRestoringDraft(false); },[]);
  useEffect(()=>{if(restoringDraft)return; try{sessionStorage.setItem('truxpylot_registration_draft',JSON.stringify({role,accountType,fullName,businessName,registrationNumber,email,phone,country,state,city,area,street,profession,yearsExperience,securityQuestion,privacyAccepted,referralCode}))}catch{}},[restoringDraft,role,accountType,fullName,businessName,registrationNumber,email,phone,country,state,city,area,street,profession,yearsExperience,securityQuestion,privacyAccepted,referralCode]);
  useEffect(()=>{if(resendCooldown<=0)return;const t=setTimeout(()=>setResendCooldown(c=>c-1),1000);return()=>clearTimeout(t)},[resendCooldown]);

  const steps=role==='PROFESSIONAL'?['Role','Account type','Personal info','Location','Professional info','Security','Verify email']:['Role','Account type','Personal info','Location','Security','Verify email'];
  const lastStep=steps.length-1;
  function next(){setError(''); if(step===0&&!role)return setError('Choose an option to continue.'); if(step===1&&!accountType)return setError('Choose an option to continue.'); if(step===2){if(accountType==='BUSINESS'&&(!businessName.trim()||!registrationNumber.trim()||!fullName.trim()||!email.trim()))return setError('Business name, registration number, contact person and email are required.');if(accountType==='INDIVIDUAL'&&(!fullName.trim()||!email.trim()))return setError('Full name and email are required.')} if(step===3&&accountType==='BUSINESS'&&(!state.trim()||!city.trim()||!street.trim()))return setError('Business accounts need a state, city and street/address before continuing.'); const securityStep=role==='PROFESSIONAL'?5:4; if(step===securityStep){if(password.length<12)return setError('Create a password with at least 12 characters.');if(!securityAnswer.trim()||securityAnswer.trim().length<2)return setError('Add an answer to your security question.');if(!privacyAccepted)return setError('Please read and accept the Privacy Policy before continuing.')} setStep(s=>Math.min(lastStep,s+1)); }
  function back(){setError('');setStep(s=>Math.max(0,s-1));}

  async function sendCode(){if(resendCooldown>0)return;setError('');setSubmitting(true);const body={mode:'register',role,accountType,fullName,email,phone:phone||undefined,businessName:accountType==='BUSINESS'?businessName:undefined,registrationNumber:accountType==='BUSINESS'?registrationNumber:undefined,country:country||undefined,state:state||undefined,city:city||undefined,area:area||undefined,street:street||undefined,profession:role==='PROFESSIONAL'?profession||undefined:undefined,yearsExperience:role==='PROFESSIONAL'&&yearsExperience?Number(yearsExperience):undefined,password,securityQuestion,securityAnswer,privacyAccepted,privacyPolicyVersion:'2026-09-01',referralCode:referralCode||undefined};try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),20000);let r:Response;try{r=await fetch('/api/auth/otp/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal})}finally{clearTimeout(timeout)}const d=await r.json().catch(()=>({error:'The service is temporarily unavailable. Please try again.'}));setSubmitting(false);if(!r.ok)return setError(d.error||'Something went wrong.');setOtpSent(true);setCode('');setResendCooldown(60)}catch(e){setSubmitting(false);setError(e instanceof DOMException&&e.name==='AbortError'?'The verification service took too long to respond. Please try again in a moment.':'Could not reach the server. Check your connection and try again.')}}
  async function verifyCode(){setError('');setSubmitting(true);try{const r=await fetch('/api/auth/otp/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,code})});const d=await r.json().catch(()=>({error:'The service is temporarily unavailable. Please try again.'}));setSubmitting(false);if(!r.ok){if(r.status===409){setOtpSent(false);setCode('')}return setError(d.error||'Something went wrong.')}try{sessionStorage.removeItem('truxpylot_registration_draft')}catch{}router.push(new URLSearchParams(window.location.search).get('next')||d.redirect||'/dashboard');router.refresh()}catch{setSubmitting(false);setError('Could not reach the server. Check your connection and try again.')}}

  return <div className="auth-form register-wizard" aria-busy={restoringDraft||submitting}>
    <p className="eyebrow">JOIN TRUX PYLOT</p><h1>Create your account</h1><p>Find work or trusted help. It only takes a minute to begin.</p>
    <div className="wizard-progress">{steps.map((label,i)=><div key={label} className={`wizard-step-dot ${i===step?'active':i<step?'done':''}`}><span>{i<step?'✓':i+1}</span>{label}</div>)}</div>
    {step===0&&<div className="role-picker"><p className="wizard-question">What are you here to do?</p><button type="button" className={`role-card ${role==='CUSTOMER'?'selected':''}`} onClick={()=>setRole('CUSTOMER')}><b>I need a professional</b><span>Find and book trusted help for a job.</span></button><button type="button" className={`role-card ${role==='PROFESSIONAL'?'selected':''}`} onClick={()=>setRole('PROFESSIONAL')}><b>I want to offer my services</b><span>Get verified and start receiving job requests.</span></button></div>}
    {step===1&&<div className="role-picker"><p className="wizard-question">{role==='PROFESSIONAL'?'Are you registering as an individual or a business?':'Are you signing up as an individual or a business?'}</p><button type="button" className={`role-card ${accountType==='INDIVIDUAL'?'selected':''}`} onClick={()=>setAccountType('INDIVIDUAL')}><b>Individual</b><span>{role==='PROFESSIONAL'?'You personally offer the service.':'You are booking for yourself.'}</span></button><button type="button" className={`role-card ${accountType==='BUSINESS'?'selected':''}`} onClick={()=>setAccountType('BUSINESS')}><b>Business / Organization</b><span>{role==='PROFESSIONAL'?'A registered company offering the service.':'You are booking on behalf of a company or estate.'}</span></button></div>}
    {step===2&&<div className="wizard-fields">{accountType==='BUSINESS'&&<><input value={businessName} onChange={e=>setBusinessName(e.target.value)} placeholder="Business / company name" required/><input value={registrationNumber} onChange={e=>setRegistrationNumber(e.target.value)} placeholder="CAC registration number" required/></>}<input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder={accountType==='BUSINESS'?'Contact person’s full name':'Full name'} required/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email address" required/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="WhatsApp phone number"/></div>}
    {step===3&&<div className="wizard-fields"><select value={country} onChange={e=>setCountry(e.target.value)}><option>Nigeria</option><option>Ghana</option><option>Other</option></select><select value={state} onChange={e=>setState(e.target.value)}><option value="">Select state</option>{NG_STATES.map(s=><option key={s} value={s}>{s}</option>)}</select><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City"/><input value={area} onChange={e=>setArea(e.target.value)} placeholder="Area / neighbourhood"/><input value={street} onChange={e=>setStreet(e.target.value)} placeholder="Street / address"/></div>}
    {role==='PROFESSIONAL'&&step===4&&<div className="wizard-fields"><input value={profession} onChange={e=>setProfession(e.target.value)} placeholder="What service do you provide? e.g. Electrician"/><input value={yearsExperience} onChange={e=>setYearsExperience(e.target.value)} type="number" min={0} max={60} placeholder="Years of experience"/><p className="hint-text">You can add skills, a bio, your photo and portfolio after signing up.</p></div>}
    {((role==='PROFESSIONAL'&&step===5)||(role!=='PROFESSIONAL'&&step===4))&&<div className="wizard-fields"><p className="hint-text"><b>Secure your account from day one.</b><br/>Use a unique password and choose a security question you can remember. Your answer is stored securely and is never visible to staff.</p><input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={12} placeholder="Create password (12+ characters, upper/lowercase, number & symbol)" autoComplete="new-password" required/><select value={securityQuestion} onChange={e=>setSecurityQuestion(e.target.value)}>{SECURITY_QUESTIONS.map(q=><option key={q}>{q}</option>)}</select><input value={securityAnswer} onChange={e=>setSecurityAnswer(e.target.value)} placeholder="Your answer" autoComplete="off" required/><label className="privacy-consent"><input type="checkbox" checked={privacyAccepted} onChange={e=>setPrivacyAccepted(e.target.checked)}/><span>I have read and accept the <a href="/privacy" target="_blank" rel="noreferrer">TruxPylot Privacy Policy</a> and understand how my information is collected and used.</span></label><p className="hint-text">Your information is used to provide, secure and improve TruxPylot. We do not sell your personal information for advertising.</p></div>}
    {step===lastStep&&<div className="wizard-fields">{!otpSent?<p className="hint-text">We&apos;ll email a 6-digit code to <b>{email}</b> to confirm ownership of your email and finish creating your account.</p>:<><p className="hint-text">Enter the 6-digit code we sent to <b>{email}</b>.</p><input value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" maxLength={6} placeholder="6-digit code" required/><p className="auth-switch"><button type="button" onClick={sendCode} disabled={submitting||resendCooldown>0}>{resendCooldown>0?`Resend code (${resendCooldown}s)`:'Didn’t get a code? Resend'}</button>{' · '}<button type="button" onClick={()=>{setOtpSent(false);setCode('');setError('');setResendCooldown(0);}}>Edit details</button></p></>}</div>}
    {error&&<p role="alert">{error}</p>}
    <div className="wizard-actions">{step>0&&<button type="button" className="wizard-back" onClick={back}>← Back</button>}{step<lastStep&&<button type="button" onClick={next}>Continue →</button>}{step===lastStep&&!otpSent&&<button type="button" onClick={sendCode} disabled={submitting}>{submitting?'Sending code…':'Send code →'}</button>}{step===lastStep&&otpSent&&<button type="button" onClick={verifyCode} disabled={submitting}>{submitting?'Verifying…':'Verify & create account →'}</button>}</div>
    <p className="auth-switch">Already have an account? <a href="/login">Sign in</a></p>
  </div>;
}
