'use client';
import { useEffect, useState } from 'react';

const QUESTIONS=['What was the name of your first pet?','What was your childhood nickname?','What was the name of your first school?','What city were you born in?'];
export function SecurityCenter({ required=false }: { required?: boolean }){
 const [data,setData]=useState<any>(null),[setup,setSetup]=useState<any>(null),[code,setCode]=useState(''),[password,setPassword]=useState(''),[currentPassword,setCurrentPassword]=useState(''),[question,setQuestion]=useState(QUESTIONS[0]),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function load(){const r=await fetch('/api/security/status',{cache:'no-store'});if(r.ok)setData(await r.json())} useEffect(()=>{load()},[]);
 async function start2fa(){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/security/2fa/setup',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error);setSetup(d)}catch(e){setError(e instanceof Error?e.message:'Could not start 2FA setup.')}finally{setBusy(false)}}
 async function verify2fa(){setBusy(true);setError('');try{const r=await fetch('/api/security/2fa/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSetup(null);setCode('');setMessage('Two-step verification is now enabled.');await load();if(required){window.location.href='/dashboard/admin'}}catch(e){setError(e instanceof Error?e.message:'Invalid authenticator code.')}finally{setBusy(false)}}
 async function disable2fa(){setBusy(true);setError('');try{const r=await fetch('/api/security/2fa/disable',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('Two-step verification disabled.');setCode('');await load()}catch(e){setError(e instanceof Error?e.message:'Could not disable 2FA.')}finally{setBusy(false)}}
 async function saveSecurity(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/security/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:currentPassword||undefined,newPassword:password||undefined,securityQuestion:question,securityAnswer:answer||undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('Security settings updated. Existing devices were signed out for your protection.');setPassword('');setCurrentPassword('');setAnswer('');}catch(e){setError(e instanceof Error?e.message:'Could not update security settings.')}finally{setBusy(false)}}
 if(!data)return <section className="panel security-panel"><p>Loading security center…</p></section>;
 return <div className="security-stack">{required&&!data.twoFactorEnabled&&<section className="security-required"><b>Action required: protect this administrator account.</b><span>Two-step verification must be enabled before you can use the Control Center.</span></section>}
 <section className="panel security-panel"><div className="panel-head"><div><h2>Account protection</h2><p>Keep your TruxPylot account protected from unauthorized access.</p></div><span className={`status ${data.twoFactorEnabled?'approved':'pending'}`}>{data.twoFactorEnabled?'2FA enabled':'2FA not enabled'}</span></div>{!data.twoFactorEnabled?<><p className="security-note">Use an authenticator app. TruxPylot stores your setup secret encrypted and never shows your recovery data to staff.</p><button className="primary" type="button" onClick={start2fa} disabled={busy}>{busy?'Preparing…':'Enable 2FA →'}</button></>:<><p className="security-note">Two-step verification is active. Keep your recovery codes somewhere safe.</p><input className="security-code-input" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} placeholder="Authenticator code"/><button className="secondary" type="button" onClick={disable2fa} disabled={busy}>Disable 2FA</button></>}{setup&&<div className="twofa-setup"><h3>Finish 2FA setup</h3><p>Add this account to your authenticator app manually.</p><div className="twofa-secret"><span>Secret key</span><code>{setup.secret}</code></div><p className="hint-text">Account: {setup.account} · Issuer: {setup.issuer}</p><p><b>Recovery codes</b></p><div className="recovery-codes">{setup.recoveryCodes.map((c:string)=><code key={c}>{c}</code>)}</div><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} placeholder="Enter 6-digit code"/><button className="primary" type="button" onClick={verify2fa} disabled={busy}>{busy?'Verifying…':'Confirm & enable 2FA'}</button></div>}</section>
 <section className="panel security-panel"><div className="panel-head"><div><h2>Password & recovery</h2><p>Use a strong unique password and a recovery question you can remember.</p></div></div><form onSubmit={saveSecurity} className="security-form">{data?.hasPassword&&<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} placeholder="Current password" autoComplete="current-password"/>}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={data?.hasPassword?'New password (12+ characters, upper/lowercase, number & symbol)':'Set password (12+ characters, upper/lowercase, number & symbol)'} minLength={12} autoComplete="new-password" required/><select value={question} onChange={e=>setQuestion(e.target.value)}>{QUESTIONS.map(q=><option key={q}>{q}</option>)}</select><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Security answer" autoComplete="off" required/><button className="primary" disabled={busy}>{busy?'Saving…':'Save security settings'}</button></form></section>
 <section className="panel security-panel"><div className="panel-head"><div><h2>Recognized devices</h2><p>Remove devices you no longer recognize.</p></div></div>{data.devices.length?data.devices.map((d:any)=><div className="security-device" key={d.id}><div><b>{d.label}</b><small>Last active {new Date(d.lastSeenAt).toLocaleString('en-NG')}</small></div><button className="secondary" onClick={async()=>{await fetch('/api/security/devices',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:d.id})});load()}}>Remove</button></div>):<div className="empty">No recognized devices yet.</div>}</section>
 <section className="panel security-panel"><div className="panel-head"><div><h2>Recent security activity</h2><p>Only activity associated with your account is shown here.</p></div></div>{data.attempts.map((a:any)=><div className="security-event" key={a.id}><span className={a.success?'ok':'bad'}>{a.success?'✓':'!'}</span><div><b>{a.action.replaceAll('_',' ')}</b><small>{new Date(a.createdAt).toLocaleString('en-NG')} · {a.riskLevel}</small></div></div>)}</section>{message&&<p className="security-success" role="status">{message}</p>}{error&&<p className="security-error" role="alert">{error}</p>}</div>
}
