'use client';
import { useEffect, useState } from 'react';

const QUESTIONS=['What was the name of your first pet?','What was your childhood nickname?','What was the name of your first school?','What city were you born in?'];
export function SecurityCenter(){
 const [data,setData]=useState<any>(null),[setup,setSetup]=useState<any>(null),[code,setCode]=useState(''),[password,setPassword]=useState(''),[currentPassword,setCurrentPassword]=useState(''),[question,setQuestion]=useState(QUESTIONS[0]),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[showAdvanced,setShowAdvanced]=useState(false);
 async function load(){const r=await fetch('/api/security/status',{cache:'no-store'});if(r.ok)setData(await r.json())}
 useEffect(()=>{load()},[]);
 async function start2fa(){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/security/2fa/setup',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error);setSetup(d)}catch(e){setError(e instanceof Error?e.message:'Could not start 2FA setup.')}finally{setBusy(false)}}
 async function verify2fa(){setBusy(true);setError('');try{const r=await fetch('/api/security/2fa/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSetup(null);setCode('');setMessage('2FA is now enabled. Your account is protected by a second sign-in step.');await load();}catch(e){setError(e instanceof Error?e.message:'Invalid authenticator code.')}finally{setBusy(false)}}
 async function disable2fa(){setBusy(true);setError('');try{const r=await fetch('/api/security/2fa/disable',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('2FA has been disabled.');setCode('');await load()}catch(e){setError(e instanceof Error?e.message:'Could not disable 2FA.')}finally{setBusy(false)}}
 async function saveSecurity(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/security/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:currentPassword||undefined,newPassword:password||undefined,securityQuestion:question,securityAnswer:answer||undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('Password and recovery settings updated.');setPassword('');setCurrentPassword('');setAnswer('');}catch(e){setError(e instanceof Error?e.message:'Could not update security settings.')}finally{setBusy(false)}}
 if(!data)return <section className="panel security-panel"><p>Loading security…</p></section>;
 return <div className="security-modern">
  <section className="security-hero-card">
   <div className="security-hero-glow" />
   <div className="security-hero-copy"><span className="security-overline">ACCOUNT SECURITY</span><h2>Keep your account one step ahead.</h2><p>Simple protection for your TruxPylot account. Turn on two-step verification and sign in with confidence.</p></div>
   <div className={`security-state-orb ${data.twoFactorEnabled?'on':''}`}><span>{data.twoFactorEnabled?'PROTECTED':'OPTIONAL'}</span><strong>{data.twoFactorEnabled?'2FA ON':'2FA OFF'}</strong><small>{data.twoFactorEnabled?'Authenticator active':'Add a second sign-in step'}</small></div>
  </section>

  <section className="security-main-card">
   <div className="security-main-top"><div className="security-icon-mark">⌁</div><div><span className="security-overline">TWO-STEP VERIFICATION</span><h3>{data.twoFactorEnabled?'Your account is protected':'Add another layer of protection'}</h3><p>{data.twoFactorEnabled?'You will enter a 6-digit code from your authenticator when signing in.':'Use an authenticator app to generate a fresh 6-digit code when you sign in.'}</p></div></div>
   {!data.twoFactorEnabled ? <button className="security-cta" type="button" onClick={start2fa} disabled={busy}><span>{busy?'Preparing setup…':'Enable 2FA'}</span><b>→</b></button> : <div className="security-enabled-row"><div><b>Authenticator protection is active</b><small>Keep your authenticator and recovery codes private.</small></div><button className="security-danger-btn" type="button" onClick={()=>setShowAdvanced(true)}>Manage</button></div>}
   {setup&&<div className="twofa-setup-modern"><div className="setup-step"><span>01</span><div><b>Add TruxPylot to your authenticator</b><p>Use Google Authenticator, Microsoft Authenticator, Authy or another TOTP app.</p></div></div><div className="setup-key-box"><div><span>SETUP KEY</span><code>{setup.secret}</code></div><button type="button" onClick={()=>navigator.clipboard?.writeText(setup.secret)}>Copy</button></div><p className="setup-account">Account: <b>{setup.account}</b> · Issuer: <b>{setup.issuer}</b></p><div className="setup-step"><span>02</span><div><b>Enter the 6-digit code</b><p>Your authenticator will generate a new code automatically.</p></div></div><input className="security-code-input-modern" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} placeholder="000000" autoComplete="one-time-code"/><button className="security-cta" type="button" onClick={verify2fa} disabled={busy}><span>{busy?'Verifying…':'Confirm & turn on 2FA'}</span><b>→</b></button><div className="recovery-modern"><b>Save your backup codes</b><p>These codes can help you recover access if you lose your authenticator.</p><div>{setup.recoveryCodes.map((c:string)=><code key={c}>{c}</code>)}</div></div></div>}
  </section>

  <section className="security-simple-grid">
   <div className="security-mini-card"><span className="security-mini-num">01</span><h3>Password</h3><p>Use a unique password with at least 12 characters.</p><form onSubmit={saveSecurity} className="security-form-modern">{data?.hasPassword&&<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} placeholder="Current password" autoComplete="current-password"/>}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={data?.hasPassword?'New password':'Create password'} minLength={12} autoComplete="new-password" required/><select value={question} onChange={e=>setQuestion(e.target.value)}>{QUESTIONS.map(q=><option key={q}>{q}</option>)}</select><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Recovery answer" autoComplete="off" required/><button className="security-outline-btn" disabled={busy}>{busy?'Saving…':'Update security'}</button></form></div>
   <div className="security-mini-card"><span className="security-mini-num">02</span><h3>Recognized devices</h3><p>Review devices that have recently accessed your account.</p><div className="device-list-modern">{data.devices.length?data.devices.slice(0,4).map((d:any)=><div className="device-row-modern" key={d.id}><div className="device-dot">●</div><div><b>{d.label}</b><small>Last active {new Date(d.lastSeenAt).toLocaleString('en-NG')}</small></div><button onClick={async()=>{await fetch('/api/security/devices',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:d.id})});load()}}>Remove</button></div>):<div className="security-empty-modern">No recognized devices yet.</div>}</div></div>
  </section>

  <section className="security-activity-card"><div className="security-activity-head"><div><span className="security-overline">SECURITY ACTIVITY</span><h3>Recent account activity</h3></div><span>{data.attempts.length} events</span></div>{data.attempts.slice(0,6).map((a:any)=><div className="security-activity-row" key={a.id}><i className={a.success?'good':'risk'}>{a.success?'✓':'!'}</i><div><b>{a.action.replaceAll('_',' ')}</b><small>{new Date(a.createdAt).toLocaleString('en-NG')} · {a.riskLevel}</small></div></div>)}</section>
  {data.twoFactorEnabled&&showAdvanced&&<div className="security-manage-sheet"><div><span className="security-overline">2FA MANAGEMENT</span><h3>Disable two-step verification?</h3><p>Enter the current authenticator code to turn it off.</p></div><input className="security-code-input-modern" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} placeholder="000000"/><div className="security-sheet-actions"><button className="security-outline-btn" onClick={()=>setShowAdvanced(false)}>Cancel</button><button className="security-danger-btn" onClick={disable2fa} disabled={busy}>Disable 2FA</button></div></div>}
  {message&&<p className="security-success-modern" role="status">✓ {message}</p>}{error&&<p className="security-error-modern" role="alert">! {error}</p>}
 </div>
}
